### ISSUE TITLE
Mapboxgl viz types roadmap

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-jupyter#4]
This ticket tracks the viz types we plan to add to the library.

Add a Python class for the following visual types

- [x] Circle map
- [ ] Graduated Circle map
    * In progress
- [ ] Clustered Circle map
- [ ] Heatmap
- [ ] Choropleth (fill map)
- [ ] Dot Density map
- [ ] Linestring map
- [ ] 3D extrusion map

**Comment by ulemanstreaming** [comment]
A strong vote for Clustered Circle maps. Dismayed to find it missing in the roadmap for 1.0.0.

Clustering is one of the best map visualization tricks to come along in recent years, making it possible to use large, global point data sets without prior subsampling or scale-based subsetting. Ideal for the data exploration stage of data science workflows.

**Comment by rselover** [comment]
@ryanbaumann - based on your profile, it looks like you've got a lot going on!

My vote is for Choropleth - do you have a sense of when Jupyter dev will get more attention?

**Comment by ryanbaumann** [comment]
@rselover heya!

Clusters and circles are next on the priority list.  We're working on some core Mapbox GL JS for data visualization abstractions that should make the python `mapboxgl` library here much more supportable and performant!  

cc @perrygeo

**Comment by ryanbaumann** [comment]
Added preliminary clustered circle viz support in https://github.com/mapbox/mapboxgl-jupyter/pull/27 cc @ulemanstreaming

**Comment by rmcarthur** [comment]
How relevant is this roadmap? Is this still the most important goal posts to look for?

**Comment by akacarlyann** [comment]
@rmcarthur I'm not sure about the general vision but this is what I reference as a volunteer contributor :). I think multi-layer maps are the highest priority. I'm actually hoping to open a PR for this soon. Hexbin visualizations have been requested somewhat recently in the Issues tracker as well.

**Comment by rmcarthur** [comment]
Are you going to fork off of #129? I really liked the approach of that, and might take a stab to fork and finish up based off the review and comments there.

**Comment by akacarlyann** [comment]
@rmcarthur Yeah I set up templates using lucasvw's api approach with `add_layer` and `remove_layer` methods.  I'm actually nearly done, with the exception of legend handling.  There's not a lot of real estate, so we'll probably have to introduce some sort of minimization of the legends.

**Comment by rmcarthur** [comment]
I've actually built something very similar and having similar things with the legend. It looks great when not in an iframe though. I look forward to your PR. I can help review and comment if you'd like. I'm very new to this repo, but needed the layering aspect so I hacked something together fairly quickly. Is there anything I can help with?

**Comment by akacarlyann** [comment]
Oh awesome! I suspect we are members of a growing club of multi-layer mapviz-hackers.  I'd really like to get my PR up sometime this week and happy to collaborate @rmcarthur!

**Comment by ryanbaumann** [comment]
> I suspect we are members of a growing club of multi-layer mapviz-hackers.

Yes, it certainly seems so!  Thank you @akacarlyann @rmcarthur for leading the charge.  Looking forward to a draft PR to review.
